### ISSUE TITLE
Syncing an Azure group only syncs the first 100 members

### ISSUE THREAD

**Issue by lehsaclarkson** [RTWA/WebApps#18]
Refer to microsoft docs for @odata.nextLink

https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http

**Comment by RobTrehy** [comment]
Please could you test this for me. As none of my groups contain more than 100 members.

Download this file: [MSGraphController.txt](https://github.com/RTWA/WebApps/files/8177233/MSGraphController.txt) - change the extension to .php

Save it to C:/inetpub/WebApps/app/Http/Controllers
Overwriting the existing file.

Go to WebApps in your browser, navigate to Settings > Microsoft Azure Integration.

Open your Browsers Developer Tools (F12) and go to the Network tab. Click on the clear icon to clear any existing results
![image](https://user-images.githubusercontent.com/13102009/156550917-e5dc893e-68e8-48c0-9dae-f8780a2ce77c.png)

Scroll to the bottom of the WebApps page, where the last sync is displayed and click the Sync now button.
Look for a result with the name of sync, like so
![image](https://user-images.githubusercontent.com/13102009/156551037-1578ac18-56ec-4836-80fe-f4df0ac7810a.png)

Yours will hopefully show a 500 status, rather than my 200 in the example.

Select the result and navigate to the Preview tab, copy and paste the resulting JSON into here for me to check please.
(The output will not display and PII of your users as that will be removed before the response)

**Comment by lehsaclarkson** [comment]
The Staus is still 200. 
Selecting the result and preview isn't showing any data

**Comment by RobTrehy** [comment]
Thanks for trying.

Could you please edit the same file (MSGraphController.php)

Move line 173 `if (isset($data['@odata.nextLink'])) {`
to below line 175 `dd($data);`

Lines 173 - 177, should now look like:
173: `unset($data['value']);`
174: `dd($data)`;
175: `if (isset($data['@odata.nextLink'])) {`
176: `$this->syncMoreGroupMembers($token, $data['@odata.nextLink'], $group);`
177: `}`

Repeat the same procedure above to get output from sync result

**Comment by lehsaclarkson** [comment]
It now just says 
Sync 500
Preview 
Server Error

**Comment by RobTrehy** [comment]
Please download this corrected version: [MSGraphController.txt](https://github.com/RTWA/WebApps/files/8178050/MSGraphController.txt)

As before, change the file extension to .php and overwrite in C:/inetpub/WebApps/app/Http/Controllers
 
Please paste results of Sync

**Comment by lehsaclarkson** [comment]
Hi, 

I can confirm that this has worked. 

Nice one

**Comment by RobTrehy** [comment]
Perfect. Thanks for testing!

The file you have will be fine for the time being. 
The fix has been added to the next release - 1.0.6.
